// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sshkznvkvzegrqhimjff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzaGt6bnZrdnplZ3JxaGltamZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDY3ODEsImV4cCI6MjA2NTUyMjc4MX0.KJ8BwH82TWLP_4jJeE4Wc4UHM0DjrXpQSQr9kxGMuXk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);